# Generated by Django 4.1.2 on 2022-10-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_comments_created_at_comments_updated_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
